name: Dominik Labudzinski
description: IT Manager & Senior Software Developer
avatar: https://avatars0.githubusercontent.com/u/1152480?s=460&v=4
footer-links:
  github: labudzinski
  github2: Effiana
  linkedin: dominik-l
disqus: labudzinski-com
google_analytics: UA-79990966-2
url: https://labudzinski.com
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-pagination
paginate: 10
paginate_files:
  - index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
