baseURL = 'https://labudzinski.com/'
languageCode = 'pl-pl'
title = 'Dominik Labudzinski'
theme = 'hermit'
[author]
  name = "Dominik Labudzinski"
[params]
  AuthorName = 'Dominik Labudzinski'
  GitHubUser = 'Labudzinski'
  ListOfFoo = ['foo1', 'foo2']
  SidebarRecentLimit = 5
  homeSubtitle = 'CTO / CSO / Senior Software Architect'
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
[[params.social]]
      name      = "github"
      icon_pack = "fab"
      url       = "https://github.com/labudzinski"
[[params.social]]
      name      = "linkedin"
      icon_pack = "fab"
      url       = "https://www.linkedin.com/in/dominik-l/"
[[params.social]]
      name      = "github"
      icon_pack = "fab"
      url       = "https://github.com/lemric"
[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
    
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
